version: '3.7'

services:
  react-front-prod:
    container_name: react-front-prod
    build:
      context: .
      dockerfile: prod.Dockerfile
    ports:
      - '80:80'
    environment:
      - NODE_ENV=production
